### ISSUE TITLE
Can I help you with CodeSniffer 3.0 support?

### ISSUE THREAD

**Issue by TomasVotruba** [webthinkgr/codesniffer#2]
I see this package is quite new. I would love to use some of yours sniffs, but 2.x is old and not developed anymore so I don't use it.

Why not upgrade it to CodeSniffer 3?

I can send PR if you say so :)

**Comment by gmponos** [comment]
I already have a branch for it. check it out

**Comment by gmponos** [comment]
https://github.com/webthinkgr/codesniffer/tree/2.x

**Comment by TomasVotruba** [comment]
Awesome! :clap: 

 When do you plan to tag it so I can use it?

**Comment by gmponos** [comment]
With the other issue about the licenses that came up I really need to clear things out about the sniffs I can use and then I will. Until then feel free to make any PR you think.

**Comment by TomasVotruba** [comment]
I understand that. I think your branch is ready to go for 3.0, so no PR needed.

You might wanna look on Slevomat CS: https://github.com/slevomat/coding-standard
The best rules I know of!

**Comment by gmponos** [comment]
Which ones are the sniffs that you are interested in?

**Comment by TomasVotruba** [comment]
From a quick check:

- https://github.com/webthinkgr/codesniffer/blob/master/Webthink/Sniffs/Tests/PrefixFunctionNameSniff.php
- maybe https://github.com/webthinkgr/codesniffer/blob/master/Webthink/Sniffs/Commenting/VariableCommentSniff.php

I see that 90% of sniffs are already made with same functionality just different parameters.

**I know setting up them might be pain - include their ruleset, must be in specific naming, composer etc., so it's easier to fork and tune.**

I want to use various sniffs from many coding standards, so I kinda uderstand the motivation. But I wanted drop the maintenance (too lazy :)). That's why I made [EasyCodingStandard](https://www.tomasvotruba.cz/blog/2017/05/03/combine-power-of-php-code-sniffer-and-php-cs-fixer-in-3-lines/) to make it easier to use than to fork. **I'd like to hear what you think about it.**

**Comment by TomasVotruba** [comment]
Closing, as there is already a branch for CodeSniffer 3.0
